# Dockerfile used to create "husyci/gosec" image
# https://hub.docker.com/r/huskyci/gosec/

FROM securego/gosec:2.22.4

RUN apk --no-cache add ca-certificates jq openssh-client

ENTRYPOINT []
CMD ["/bin/sh"]
